# Generated by Django 5.1.3 on 2024-12-31 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_account_name_customuser_name_customuser_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='default_user', max_length=255, unique=True),
        ),
    ]
